CREATE TABLE items (
    item_code VARCHAR(70) NOT NULL COMMENT '商品コード',
    item_name VARCHAR(500) NOT NULL COMMENT '商品名',
    item_url VARCHAR(255) DEFAULT NULL COMMENT '商品URL',
    item_price_max BIGINT(10) NOT NULL COMMENT '商品価格最大',
    item_price_min BIGINT(10) NOT NULL  COMMENT '商品価格最低',
    affiliate_url VARCHAR(255) DEFAULT NULL COMMENT 'アフィリエイトURL ',
    image_flag VARCHAR(1) NOT NULL COMMENT '商品画像フラグ(0: 画像無、1:  画像有)',
    medium_image_url VARCHAR(255) DEFAULT NULL COMMENT '1枚目の商品画像',
    tax_flag TINYINT NOT NULL COMMENT '税込みフラグ(0: 税込、1: 税別)',
    postage_flag TINYINT NOT NULL COMMENT '送料フラグ(0: 送料込、1: 送料別)',
    credit_card_flag TINYINT NOT NULL COMMENT 'クレカ利用可フラグ(0: 不可、1: 可)',
    start_time DATETIME DEFAULT NULL COMMENT 'タイムセール開始時刻',
    end_time DATETIME DEFAULT NULL COMMENT 'タイムセール終了時刻',
    review_count INT NOT NULL COMMENT 'レビュー件数',
    review_average DECIMAL(3, 2) NOT NULL COMMENT 'レビュー平均',
    point_rate DECIMAL(4, 1) NOT NULL COMMENT '商品別ポイント倍率',
    point_rate_start_time DATETIME DEFAULT NULL COMMENT '商品別ポイント倍率変更開始日時',
    point_rate_end_time DATETIME DEFAULT NULL COMMENT '商品別ポイント倍率変更終了日時',
    shop_name VARCHAR(255) NOT NULL COMMENT '店舗名',
    shop_code VARCHAR(100) NOT NULL COMMENT '店舗コード',
    shop_url VARCHAR(255) DEFAULT NULL COMMENT '店舗URL',
    shop_affiliate_url VARCHAR(255) DEFAULT NULL COMMENT 'アフィリエイト店舗URL',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'レコード作成日時',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'レコード更新日時',
    PRIMARY KEY (item_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;